name: Deploy pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy the game
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - name: Push to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: game # The directory of the generated static files
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Deploy: ({sha}) {msg}" # The commit message